In [1]:
import pandas as pd

In [9]:
transformed_housing_data_2=pd.read_csv("transformed_housing_data_2.csv")

In [51]:
transformed_housing_data_2

,Sale_Price,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,No of Times Visited,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),...,Waterfront_View_Yes,Zipcode_group_Zipcode_group_1,Zipcode_group_Zipcode_group_2,Zipcode_group_Zipcode_group_3,Zipcode_group_Zipcode_group_4,Zipcode_group_Zipcode_group_5,Zipcode_group_Zipcode_group_6,Zipcode_group_Zipcode_group_7,Zipcode_group_Zipcode_group_8,Zipcode_group_Zipcode_group_9
0,221900.0,3,1.00,1180.0,5650.0,1.0,0,7,1180.0,0,...,0,0,0,0,0,0,0,0,0,0
1,538000.0,3,2.25,2570.0,7242.0,2.0,0,7,2170.0,400,...,0,0,1,0,0,0,0,0,0,0
2,180000.0,2,1.00,770.0,10000.0,1.0,0,6,770.0,0,...,0,0,1,0,0,0,0,0,0,0
3,604000.0,4,3.00,1960.0,5000.0,1.0,0,7,1050.0,910,...,0,0,0,1,0,0,0,0,0,0
4,510000.0,3,2.00,1680.0,8080.0,1.0,0,8,1680.0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21604,360000.0,3,2.50,1530.0,1131.0,3.0,0,8,1530.0,0,...,0,0,0,1,0,0,0,0,0,0
21605,400000.0,4,2.50,2310.0,5813.0,2.0,0,8,2310.0,0,...,0,1,0,0,0,0,0,0,0,0
21606,402101.0,2,0.75,1020.0,1350.0,2.0,0,7,1020.0,0,...,0,0,0,1,0,0,0,0,0,0
21607,400000.0,3,2.50,1600.0,2388.0,2.0,0,8,1600.0,0,...,0,0,0,0,1,0,0,0,0,0
21608,325000.0,2,0.75,1020.0,1076.0,2.0,0,7,1020.0,0,...,0,0,0,1,0,0,0,0,0,0

## seperating dependent and Independent varible:

Y: dependent variable
X: is indepedent variable

In [14]:
Y=transformed_housing_data_2.iloc[:,0]

In [24]:
X=transformed_housing_data_2.iloc[:,1:31]

In [27]:
X.head(5)

,No of Bedrooms,No of Bathrooms,Flat Area (in Sqft),Lot Area (in Sqft),No of Floors,No of Times Visited,Overall Grade,Area of the House from Basement (in Sqft),Basement Area (in Sqft),Age of House (in Years),...,Waterfront_View_Yes,Zipcode_group_Zipcode_group_1,Zipcode_group_Zipcode_group_2,Zipcode_group_Zipcode_group_3,Zipcode_group_Zipcode_group_4,Zipcode_group_Zipcode_group_5,Zipcode_group_Zipcode_group_6,Zipcode_group_Zipcode_group_7,Zipcode_group_Zipcode_group_8,Zipcode_group_Zipcode_group_9
0,3,1.00,1180.0,5650.0,1.0,0,7,1180.0,0,63,...,0,0,0,0,0,0,0,0,0,0
1,3,2.25,2570.0,7242.0,2.0,0,7,2170.0,400,67,...,0,0,1,0,0,0,0,0,0,0
2,2,1.00,770.0,10000.0,1.0,0,6,770.0,0,85,...,0,0,1,0,0,0,0,0,0,0
3,4,3.00,1960.0,5000.0,1.0,0,7,1050.0,910,53,...,0,0,0,1,0,0,0,0,0,0
4,3,2.00,1680.0,8080.0,1.0,0,8,1680.0,0,31,...,0,0,0,0,1,0,0,0,0,0

## Train and Test Datasets:

In [29]:
from sklearn.model_selection import train_test_split

In [31]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3)

In [37]:
X_train.shape

(15126, 30)

In [38]:
X_test.shape

(6483, 30)

In [35]:
Y_train.shape

(15126,)

In [39]:
Y_test.shape

(6483,)

## Feature Scaling:
1. the varibales are scaled to have similar magnitute and ranges so that the model not baised towards one varibale
2. feature scaling is must requireds in algo in which distance from datapoints is needed eg. linear regression, logistic reg, K nearest algo,principal component analysis,decision tree.etc
3. its not required for random forest ,decision tree etc

## Methods:
1.standerdisation
2.minmax scaling
3.normalization

## feature scaling using python: standerdisation

we use staderdisation for building linear reg model as model assume input variables should normally distrubuted

In [42]:
from sklearn import preprocessing
scale=preprocessing.StandardScaler()

In [43]:
X_train=scale.fit_transform(X_train)

In [47]:
X_train

array([[-1.47209648,  0.4976704 , -0.76013087, ..., -0.1112746 ,
        -0.17002823, -0.05084296],
       [ 0.66484511, -0.47181906,  0.35334925, ..., -0.1112746 ,
        -0.17002823, -0.05084296],
       [-1.47209648, -1.44130851, -0.33852189, ..., -0.1112746 ,
        -0.17002823, -0.05084296],
       ...,
       [ 1.7333159 ,  2.75981246,  2.78570875, ..., -0.1112746 ,
         5.88137639, -0.05084296],
       [-0.40362569, -0.1486559 ,  0.22362341, ..., -0.1112746 ,
        -0.17002823, -0.05084296],
       [-1.47209648, -1.44130851, -0.92228817, ..., -0.1112746 ,
        -0.17002823, -0.05084296]])

In [49]:
X_test=scale.fit_transform(X_test)

In [50]:
X_test

array([[ 0.70513145,  0.5066615 ,  0.01967526, ..., -0.11457334,
        -0.16607121, -0.04122656],
       [-0.38719046,  0.5066615 ,  0.75101608, ..., -0.11457334,
        -0.16607121, -0.04122656],
       [-0.38719046,  0.5066615 , -0.15761949, ..., -0.11457334,
        -0.16607121, -0.04122656],
       ...,
       [-0.38719046, -1.46237827, -1.33219717, ..., -0.11457334,
        -0.16607121, -0.04122656],
       [-1.47951237,  0.5066615 , -0.76707017, ..., -0.11457334,
        -0.16607121, -0.04122656],
       [-0.38719046, -0.47785838, -0.14653856, ..., -0.11457334,
        -0.16607121, -0.04122656]])